# Generated by Django 5.0.1 on 2024-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_be', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent', to='tree_be.node'),
        ),
    ]
