# Generated by Django 5.0.1 on 2024-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_be', '0002_alter_node_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
